name: Helm Chart Releaser

on:
  push:
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v1

    - name: Configure Git
      run: |
        git config user.name "$GITHUB_ACTOR"
        git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
        
    - name: Helm Chart Releaser
      uses: helm/chart-releaser-action@v1.0.0-alpha.2
      with:
        # version: # The chart-releaser version to use (default: v0.2.3)
        charts_dir: charts # optional, default is charts
        charts_repo_url: https://charts.antive.tech
        
      env:
        CR_TOKEN: "${{ secrets.CR_TOKEN }}"
